import {
  Gauge,
  RotateCw,
  Thermometer,
  Stethoscope,
  Zap,
  ArrowDownUp,
  Weight,
  Wind,
  PlugZap,
  Beaker,
  Radio,
  Wrench,
  Sun,
  Atom,
  Ruler,
  Flashlight,
  Waves,
  Activity,
  type LucideIcon,
} from "lucide-react";

// The 18 calibration specialties shown in the "expertise" grid (homepage +
// About page), matching the structure of the reference site's "Our
// Expertise" section, translated to Persian/English for our own content.
export const calibrationQuantities: { key: string; Icon: LucideIcon }[] = [
  { key: "pressure", Icon: Gauge },
  { key: "torque", Icon: RotateCw },
  { key: "temperature", Icon: Thermometer },
  { key: "medical", Icon: Stethoscope },
  { key: "electrical", Icon: Zap },
  { key: "load", Icon: ArrowDownUp },
  { key: "massBalance", Icon: Weight },
  { key: "gas", Icon: Wind },
  { key: "highVoltage", Icon: PlugZap },
  { key: "volume", Icon: Beaker },
  { key: "rf", Icon: Radio },
  { key: "generalTM", Icon: Wrench },
  { key: "optical", Icon: Sun },
  { key: "particleCounter", Icon: Atom },
  { key: "dimensional", Icon: Ruler },
  { key: "laserPowerMeters", Icon: Flashlight },
  { key: "flow", Icon: Waves },
  { key: "pdInstruments", Icon: Activity },
];
